[server]
host = "127.0.0.1"
port = 8080

[logging]
level = "info"
file = "sparkping.log"

[database]
path = "./tsink-data"

[[targets]]
address = "192.168.83.11"
name = "Router"

[[targets]]
address = "192.168.83.12"

[[targets]]
address = "192.168.83.13"
name = "NAS Server"
