name: SparkPing
version: "0.1.50"
slug: sparkping
image: ghcr.io/hco/sparkping
description: Network latency and packet loss monitoring tool
arch:
  - aarch64
  - amd64
init: false
host_network: true
privileged:
  - NET_RAW
ingress: true
ingress_port: 8080
ingress_stream: true
panel_icon: mdi:chart-line
options:
  log_level: "info"
  ingress_only: true
schema:
  log_level: list(trace|debug|info|warn|error)
  ingress_only: bool
